language: node_js
node_js:
  - node
services: 
  - docker

before_install:
  - echo "progress=false" >> ~/.npmrc

install:
  - docker build -t jeducker/docker-react-dev -f Dockerfile.dev .

script:
  - docker run jeducker/docker-react-dev npm run test -- --coverage