language: node_js
node_js:
  - 18
cache: npm
services:
  - docker

before_install:
  - docker build -t jeducker/docker-react -f Dockerfile .

script:
  - docker run -e CI=true jeducker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-2"
  env: "docker-react-2-env"
  bucket_name: "elasticbeanstalk-us-east-1-096220112091"
  bucket_path: "docker-react-2"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
