language: node_js
node_js:
  - node
services: 
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

install:
  - docker build -t jeducker/docker-react-dev -f Dockerfile.dev .

script:
  - docker run jeducker/docker-react-dev npm run test -- --coverage